spring:
  application:
    name: config-prod
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://localhost:8763/eureka
    fetch-registry: true
    register-with-eureka: true
